# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rinvGauss <- function(nu, lambda) {
    .Call('_h2D2_rinvGauss', PACKAGE = 'h2D2', nu, lambda)
}

h2D2_pretrain <- function(h2D2, W, NbetaHat, pre_mcmc_n = 200L, pre_use = 100L, pre_p = 0.05, pre_maxiter = 10L, stepsize = 2, seed = 428L) {
    invisible(.Call('_h2D2_h2D2_pretrain', PACKAGE = 'h2D2', h2D2, W, NbetaHat, pre_mcmc_n, pre_use, pre_p, pre_maxiter, stepsize, seed))
}

h2D2_sampling <- function(h2D2, W, NbetaHat, mcmc_n = 100L, thin = 1L, stepsize = 2, seed = 428L) {
    invisible(.Call('_h2D2_h2D2_sampling', PACKAGE = 'h2D2', h2D2, W, NbetaHat, mcmc_n, thin, stepsize, seed))
}

