# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rinvGauss <- function(nu, lambda) {
    .Call('_h2D2_rinvGauss', PACKAGE = 'h2D2', nu, lambda)
}

propose_lognormal <- function(x, stepsize = 2) {
    .Call('_h2D2_propose_lognormal', PACKAGE = 'h2D2', x, stepsize)
}

h2D2_sampling <- function(h2D2, L, mcmc_n = 100L, thin = 1L, stepsize = 2, scale2 = 1, seed = 428L) {
    invisible(.Call('_h2D2_h2D2_sampling', PACKAGE = 'h2D2', h2D2, L, mcmc_n, thin, stepsize, scale2, seed))
}

